/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MASTER
 */
public class Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form.class.getName());

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        confirmBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        accepTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tryText = new javax.swing.JTextField();
        tryesLabel = new javax.swing.JLabel();
        wordTxt = new javax.swing.JPasswordField();
        startBtn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        confirmBtn.setFont(new java.awt.Font("Linux Biolinum G", 0, 12)); // NOI18N
        confirmBtn.setText("Confirmar");
        confirmBtn.setEnabled(false);
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Linux Biolinum G", 0, 12)); // NOI18N
        jLabel1.setText("Letras corretas");

        accepTxt.setText(" ");
        accepTxt.setToolTipText("");
        accepTxt.setEnabled(false);
        accepTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Linux Biolinum G", 0, 12)); // NOI18N
        jLabel2.setText("Digite uma letra");

        tryText.setText(" ");
        tryText.setEnabled(false);
        tryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryTextActionPerformed(evt);
            }
        });

        tryesLabel.setFont(new java.awt.Font("Linux Biolinum G", 0, 12)); // NOI18N
        tryesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tryesLabel.setText("0");
        tryesLabel.setToolTipText("");

        wordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordTxtActionPerformed(evt);
            }
        });

        startBtn.setFont(new java.awt.Font("Linux Biolinum G", 0, 12)); // NOI18N
        startBtn.setText("Começar");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tryText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(wordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(tryesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tryesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addComponent(confirmBtn)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tryTextActionPerformed

    private void accepTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accepTxtActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        String trytext = tryText.getText().toLowerCase();
        String estadoAtual = accepTxt.getText();
        
        if(trytext.length() > 1) {
            if(trytext.equals(palavra)){
                accepTxt.setText(palavra);
                tryText.setText("PARABÉNS !!!");
                
                tryText.setEnabled(false);
                confirmBtn.setEnabled(false);
                wordTxt.setEnabled(true);
                startBtn.setEnabled(true);
            }
            tryes++;
            tryesLabel.setText(String.valueOf(tryes));
        } else {
            StringBuilder novoEstado = new StringBuilder(estadoAtual);
            char letra = trytext.charAt(0);
            
            for (int i = 0; i < palavra.length(); i++) {
                if (palavra.charAt(i) == letra) {
                    novoEstado.setCharAt(i, palavra.charAt(i));
                }
            }
            
            if(trytext.equals(estadoAtual)) {
                accepTxt.setText(palavra);
                tryText.setText("PARABÉNS !!!");
                
                tryText.setEnabled(false);
                confirmBtn.setEnabled(false);
                wordTxt.setEnabled(true);
                startBtn.setEnabled(true);
            }
            
            accepTxt.setText(novoEstado.toString());
            tryText.setText("");
            tryes++;
            tryesLabel.setText(String.valueOf(tryes));
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void wordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordTxtActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        char[] senhaChars = wordTxt.getPassword();
        palavra = new String(senhaChars).replace(" ", "");
        
        StringBuilder tracos = new StringBuilder();
        for (int i = 0; i < palavra.length(); i++) {
            tracos.append("-");
        }
        accepTxt.setText(tracos.toString());
        
        wordTxt.setEnabled(false);
        startBtn.setEnabled(false);
        confirmBtn.setEnabled(true);
        tryText.setEnabled(true);
        tryText.setText("");
        tryesLabel.setText("0");
        tryes = 0;
    }//GEN-LAST:event_startBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form().setVisible(true));
    }
    
    private String palavra;
    private int tryes;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accepTxt;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton startBtn;
    private javax.swing.JTextField tryText;
    private javax.swing.JLabel tryesLabel;
    private javax.swing.JPasswordField wordTxt;
    // End of variables declaration//GEN-END:variables
}
